'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { IonPhaser as IonPhaserElement, defineCustomElement as defineIonPhaser } from "@ion-phaser/core/dist/components/ion-phaser.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IonPhaserEvents = NonNullable<unknown>;

export const IonPhaser: StencilReactComponent<IonPhaserElement, IonPhaserEvents> = /*@__PURE__*/ createComponent<IonPhaserElement, IonPhaserEvents>({
    tagName: 'ion-phaser',
    elementClass: IonPhaserElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as IonPhaserEvents,
    defineCustomElement: defineIonPhaser
});
