/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  GameInstance,
} from './components/models';


export namespace Components {

  interface IonPhaser {
    'destroy': () => void;
    'game': GameInstance;
    'initialize': boolean;
  }
  interface IonPhaserAttributes extends StencilHTMLAttributes {
    'game'?: GameInstance;
    'initialize'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'IonPhaser': Components.IonPhaser;
  }

  interface StencilIntrinsicElements {
    'ion-phaser': Components.IonPhaserAttributes;
  }


  interface HTMLIonPhaserElement extends Components.IonPhaser, HTMLStencilElement {}
  var HTMLIonPhaserElement: {
    prototype: HTMLIonPhaserElement;
    new (): HTMLIonPhaserElement;
  };

  interface HTMLElementTagNameMap {
    'ion-phaser': HTMLIonPhaserElement
  }

  interface ElementTagNameMap {
    'ion-phaser': HTMLIonPhaserElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
